AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  PersonTable:
    Type: "AWS::Serverless::SimpleTable"
  
  PutPerson:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python3.6
      Handler: src/PutPerson.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref PersonTable
      Events:
        PutPerson:
          Type: Api
          Properties:
            Path: /
            Method: POST
  
  GetPerson:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python3.6
      Handler: src/GetPerson.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref PersonTable
      Events:
        GetPerson:
          Type: Api
          Properties:
            Path: /
            Method: GET